apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: {{ include "sim-stack.poolName" . }}
  labels:
    {{- include "sim-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sim-stack.simulatorLabels" . | nindent 6 }}
  endpointPickerRef:
    name: {{ .Release.Name }}-epp
    port:
      number: 9002
  targetPorts:
    - number: {{ .Values.simulator.port }}
