{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-simulator
  labels:
    {{- include "sim-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sim-stack.simulatorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
{{- end }}
