{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-epp
  labels:
    {{- include "sim-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sim-stack.eppLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
{{- end }}
