apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-monitor
  namespace: monitoring-alerts
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cuda-runtime
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-2b-instruct
      args:
        - --max-num-seqs=20
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          cpu: "500m"
          memory: 8Gi
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
