apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-monitor
  namespace: monitoring-metrics
  annotations:
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: granite-monitor
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      runtime: vllm-runtime
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-2b-instruct
      args:
        - --max-model-len
        - "4096"
        - --dtype
        - float16
        - --gpu-memory-utilization
        - "0.90"
        - --enforce-eager
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
