apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-custom-distribution
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        # Inference provider: vLLM
        - name: VLLM_URL
          value: 'http://llama-32-3b-instruct-predictor.my-first-model.svc.cluster.local:8080/v1'
        - name: INFERENCE_MODEL
          value: llama-32-3b-instruct
        - name: VLLM_TLS_VERIFY
          value: 'false'
        # Embeddings: inline with sentence-transformers
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: "true"
        - name: EMBEDDING_PROVIDER
          value: "sentence-transformers"
        # PostreSQL DB for metadata store
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: llamastack
        - name: POSTGRES_USER
          value: llamastack
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
      name: llama-stack
      port: 8321
    distribution:
      name: 'rh-dev'
    # storage:
    #   size: 20Gi
    #   mountPath: <custom-mount-path> ## Defaults to /opt/app-root/src/.llama/distributions/rh/