FROM registry.redhat.io/rhaii/vllm-cuda-rhel9:3.4.0

COPY --chown=1001:0 ./custom-qwen3-plugin/ /tmp/custom-qwen3-plugin/
RUN pip install --no-cache-dir /tmp/custom-qwen3-plugin/ && \
    rm -rf /tmp/custom-qwen3-plugin/