apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-monitor
  namespace: monitoring-metrics
  annotations:
    serving.kserve.io/deploymentMode: Serverless
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: oci://registry.ocp4.example.com:8443/redhattraining/granite-3.3-2b-instruct:latest
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"
