apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: monitoring-metrics
  namespace: monitoring-metrics
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      storageUri: oci://quay.io/redhattraining/oci-models/qwen3_0.6b
      resources:
        requests:
          cpu: 500m
          memory: 8Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "4"
          memory: 12Gi
          nvidia.com/gpu: "1"
