apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: l4-gpu
spec:
  nodeLabels:
    nvidia.com/gpu.product: NVIDIA-L4
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
