{{- if and .Values.nfd.enabled (not (lookup "v1" "Namespace" "" .Values.nfd.namespace)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nfd.namespace }}
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "rhoai.labels" . | nindent 4 }}
{{- end }}
