{{- if and .Values.nfd.enabled (not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.nfd.namespace "openshift-nfd")) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd
  namespace: {{ .Values.nfd.namespace }}
  labels:
    {{- include "rhoai.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Values.nfd.namespace }}
{{- end }}
