{{- if and .Values.rhoai.enabled (not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.rhoai.namespace "rhods-operator")) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: {{ .Values.rhoai.namespace }}
  labels:
    {{- include "rhoai.labels" . | nindent 4 }}
spec: {}
{{- end }}
