{{- if and .Values.serverless.enabled (not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.serverless.namespace "").items) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless
  namespace: {{ .Values.serverless.namespace }}
  labels:
    {{- include "rhoai.labels" . | nindent 4 }}
spec: {}
{{- end }}
