{{- if and .Values.servicemesh3.enabled (not (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-operators" "servicemeshoperator3")) }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
  labels:
    {{- include "rhoai.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.servicemesh3.channel }}
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: {{ .Values.catalog.source }}
  sourceNamespace: {{ .Values.catalog.sourceNamespace }}
  {{- if .Values.servicemesh3.startingCSV }}
  startingCSV: {{ .Values.servicemesh3.startingCSV }}
  {{- end }}
{{- end }}
