apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  annotations:
    opendatahub.io/dashboard-feature-visibility: '[]'
    opendatahub.io/description: >-
      A restricted CPU profile for lightweight tasks and non-GPU workloads.
      Offers 10m CPU and 1 GiB of memory by default, scaling up to 2 CPUs
      and 4 GiB of memory.
    opendatahub.io/disabled: "false"
    opendatahub.io/display-name: Restricted CPU
    opendatahub.io/managed: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
  name: restricted-cpu-profile
  namespace: redhat-ods-applications
spec:
  identifiers:
  - defaultCount: 10m
    displayName: CPU
    identifier: cpu
    maxCount: 2
    minCount: 10m
    resourceType: CPU
  - defaultCount: 1Gi
    displayName: Memory
    identifier: memory
    maxCount: 4Gi
    minCount: 512Mi
    resourceType: Memory
